site_name: package-docs 패키지 매뉴얼

site_url: https://joohyeonghan-88.github.io/package-docs/

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google 
            show_root_heading: true  # 루트 모듈 헤딩 표시
            show_symbol_type_heading: true  # 심볼 타입별 헤딩 표시
            show_source: false  # 소스 코드 보기

nav:
  - Home: index.md
  - API Reference:
    - Overview: api/overview.md
    - dataio: api/dataio/overview.md
    - analyzer:
      - Overview: api/analyzer/overview.md
      - Alpha:
        - Overview: api/analyzer/Alpha/overview.md
        - Alpha.analysis: api/analyzer/Alpha/analysis.md
        - Alpha.query: api/analyzer/Alpha/query.md

extra:
  copyright: Copyright © 2026 Joohyeong Han

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition  #  팁, 경고, 노트 등 강조 박스 생성
  # - footnotes  # 문서 하단에 각주 추가. 
  # - codehilite:  #  코드 블록에 하이라이팅 및 라인 번호 추가 (Pygments 기반)
  #     guess_lang: false
  #     linenums: true
  # - toc:  #  문서 내 헤더(#)를 기반으로 목차 자동 생성.
  #     permalink: true